---
- name: privatekey
  hosts: localhost
  vars:
     - db_username: pavan
     - db_password: passwd
  
  tasks:
  - name: Load db_password secret into variable
    shell: "kubectl create secret generic db-secret --from-literal username={{ db_username }} --from-literal passwd={{ db_password }} -n default --dry-run=client -o yaml>db-secret.yaml"
    register: db_secret

  - debug: 
      msg: "{{ db_secret }}"
  
  - name: Step-2
    shell: "kubeseal --scope namespace-wide --format yaml </home/ubuntu/ansible/secret/db-secret.yaml> sealed-db-secret2.yaml"
    register: db_secret_2

  - debug:
      msg: " {{ db_secret_2 }} "


  - name: encoding pem file
    shell: "kubectl create secret generic private-pem --from-file=/home/ubuntu/ansible/secret/Dockerkey.pem -n default --dry-run=client -o yaml>private-pem.yaml"
    register: private_pem

  - debug:
      msg:  "{{ private_pem }}" 

  - name: coping to sealed yaml file
    shell: "kubeseal --scope namespace-wide --format yaml </home/ubuntu/ansible/secret/private-pem.yaml> sealed-private-pem.yaml"
    register: seal_private_pem
  - debug:
      msg: " {{ seal_private_pem }} "

